runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /.well-known/acme-challenge
  static_dir: acme-challenge
  mime_type: text/plain

- url: /(.*).(html|js|json|css)
  static_files: \1.\2
  upload: (.*)\.(html|js|json|css)
  secure: always

- url: /(.*/?)?
  static_files: index.html
  upload: index\.html
  secure: always

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?bower\.json
- ^(.*/)?.*~
- ^(.*/)?.*\.py[cod]
- ^(.*/)?\..*
- ^(.*/)?node_modules/.*
- ^(.*/).md
- ^(.*/)LICENSE
