application: resume-v2
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /?
  static_files: index.html
  upload: /index.html

- url: /resume-print/?
  static_files: resume-print/index.html
  upload: /resume-print/.*

- url: /(.*)
  static_files: \1
  upload: .*
