application: resume-v2
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /?
  static_files: index.html
  upload: /index.html

- url: /resume/?
  static_files: resume/index.html
  upload: /resume/.*

- url: /(.*)
  static_files: \1
  upload: .*
